### ISSUE TITLE
Are there any benefits to using this transformer vs say: typed-html

### ISSUE THREAD

**Issue by danielbodart** [LeDDGroup/typescript-transform-jsx#5]
Are there any benefits to using this transformer vs https://github.com/nicojs/typed-html.

Maybe zero runtime dependencies?

Thanks

**Comment by danielpa9708** [comment]
Yep, I'll try to do a public benchmark soon. This one is super fast compared to typed-html( I even tried to make one like this but realized it was too slow so I came up with this transformer... https://github.com/danielpa9708/jsx-to-str ). The difference is that the transformer is compilation time, so it's pretty much O(1) in run time. And the other ( typed-html or jsx-to-str ) is run-time, and it makes several function calls for creating the elements.

I've done some benchmark a time ago between this transformer, jsx-to-str and pug with precompilation, and this where the results:
- transfomer: the fastest.
- pug with precompilation: fast but not as much as the transformer.
- jsx-to-str: the slowest by far, and it gets more slower as more nested elements you use.
